version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql
    expose:
      - 80

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/phpmyadmin.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - phpmyadmin

volumes:
  mysql-data:

networks:
  setup-mysql_default:
    external: true

